generate:
	mkdir -p output
	find pages -type f -name '*.cfg' -print0 | sort -zr | xargs -0 saait
	cp style.css print.css output/

view:
	$(BROWSER) output/index.html

sync:
	rsync -av output/ hiltjo@cow:/home/www/domains/www.codemadness.org/htdocs/
